export const navLinks = [
    {
        id:1,
        url:"#",
        label:"Home",
    },
    {
        id:2,
        url:"/about",
        label:"About",
    },
    {
        id:3,
        url:"/courses",
        label:"Courses",
    },
    {
        id:4,
        url:"/news",
        label:"News/Updates",
    },
    {
        id:5,
        url:"/contact",
        label:"Contact",
    },
]